### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: maitri Bootloader
interface_branding_color: 82aaff
interface_help_color: 82aaff
interface_help_color_bright: 82aaff
hash_mismatch_panic: no

term_background: 1e1e1e
backdrop: 1e1e1e

# Terminal colors (maitri Spark palette)
term_palette: 161b28;ff6e6e;7de38b;ffd479;82aaff;c99bff;6fe6d9;b8bed0
term_palette_bright: 2c3548;ff8b8b;9ceba6;ffe099;a0c0ff;dbb6ff;97f0e6;ffffff

# Text colors
term_foreground: e6e9f0
term_foreground_bright: ffffff
term_background_bright: 25324b
